const products = [
  {
    id: 1,
    name: "White T-Shirt",
    type: "shirt",
    sizes: ["M", "L"],
    color: "white",
    image: "../assets/images/white_shirt.jpg",
    price: 65,
  },
  {
    id: 2,
    name: "White T-Shirt",
    type: "shirt",
    sizes: ["S", "XL"],
    color: "white",
    image: "../assets/images/white_shirt_2.jpg",
    price: 30,
  },
  {
    id: 3,
    name: "Black T-Shirt",
    sizes: ["M"],
    color: "black",
    image: "../assets/images/black_shirt.jpg",
    price: 50,
  },
  {
    id: 4,
    name: "Black T-Shirt",
    sizes: ["S", "XXL"],
    color: "black",
    image: "../assets/images/black_shirt_2.jpg",
    price: 24,
  },
  {
    id: 5,
    name: "Washed Out Black Jeans",
    sizes: ["S", "M", "L", "XXL"],
    color: "washed",
    image: "../assets/images/washed_pants.jpg",
    price: 70,
  },
  {
    id: 6,
    name: "Ripped Grey Jeans",
    sizes: ["S", "XXL"],
    color: "grey",
    image: "../assets/images/ripped_pants.jpg",
    price: 35,
  },
  {
    id: 7,
    name: "Blue Pants",
    sizes: ["XXL"],
    color: "blue",
    image: "../assets/images/blue_pants.jpg",
    price: 140,
  },
  {
    id: 8,
    name: "Black Pants",
    sizes: ["S", "M"],
    color: "black",
    image: "../assets/images/black_pants.jpg",
    price: 15,
  },
];
